kind: pipeline
type: docker
name: prod

steps:
- name: build and publish
  image: plugins/docker
  environment:
    PUBLIC_CF_TURNSTILE_KEY:
      from_secret: CF_TURNSTILE_KEY
    CF_TURNSTILE_SECRET:
      from_secret: CF_TURNSTILE_SECRET
  settings:
    repo: harbor.everbuild.org/private/everbuild-homepage
    registry: harbor.everbuild.org/private
    username: robot$continous-integration
    password: 
      from_secret: regcred
    dockerfile: Dockerfile
    build_args_from_env:
      - PUBLIC_CF_TURNSTILE_KEY
      - CF_TURNSTILE_SECRET
    tags:
      - 1.1.0
