kind: pipeline
type: docker
name: prod

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      repo: harbor.everbuild.org/private/everbuild-homepage
      registry: harbor.everbuild.org/private
      username: robot$continous-integration
      password:
        from_secret: regcred
      dockerfile: Dockerfile
      tags:
        - 2.0.0
