<script>
    import {locale} from "svelte-i18n";
    import {t} from "$lib/i18n";
</script>

<svelte:head>
    <title>{$t("head.title.terms")}</title>
    <meta name="description" content="Everbuild | Homepage">
</svelte:head>

<div class="pt-12">
    <div class="max-w-[1200px] m-auto p-3 prose pt-6">
        {#if $locale === 'de'}
            <p style="text-align: center;"><strong>ALLGEMEINE GESCHÄFTSBEDINGUNGEN VON</strong></p>
            <p style="text-align: center;"><strong><em style="text-align: left;"><span id="span_id_url_interneteite">https://Everbuild.org</span></em></strong></p>
            <p style="text-align: left;"><em><br>Willkommen bei <span id="span_id_name_online_shop">Everbuild</span>!</em></p>

            <p style="text-align: left;"><strong><br>§ 1 </strong><strong>Geltungsbereich und Anbieter</strong></p>
            <p>(1) Die Allgemeinen Geschäftsbedingungen (nachfolgend „AGB" genannt) regeln den Verkauf von Produkten und Dienstleistungen durch <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> (nachfolgend Anbieter) an Sie, in ihrer zum Zeitpunkt der Bestellung gültigen Fassung.</p>
            <p style="text-align: left;">(2) Abweichende AGB des Bestellers werden zurückgewiesen.</p>
            <p>(3) Bitte lesen Sie diese Bedingungen aufmerksam, bevor Sie eine Bestellung an <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> aufgeben. Durch Aufgabe einer Bestellung an <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> erklären Sie sich mit der Anwendung dieser AGB auf Ihre Bestellung einverstanden.</p>
            <p>(4) Auf <span id="span_id_name_online_shop">Everbuild</span> bieten wir Ihnen den Verkauf von folgenden Produkten an:</p>
            <p style="padding-left: 30px;"><span id="span_id_produkte_beschreiben_hier">Online-Software</span></p>
            <p>(5) Auf <span id="span_id_name_online_shop">Everbuild</span> bieten wir Ihnen folgende Dienstleistungen an:</p>
            <p style="padding-left: 30px;"><span id="span_id_dienstleistungen_beschreiben_hier">Auftragsentwicklung</span></p>
            <p style="text-align: left;"><strong><br>§ 2 </strong><strong>Zustandekommen des Vertrages</strong></p>
            <p>(1) Verträge auf diesem Portal können ausschließlich in deutscher und englischer Sprache abgeschlossen werden.</p>
            <p>(2) Die Angebote richten sich ausschließlich an Endkunden mit einer Rechnungs- und Lieferanschrift in:</p>
            <p style="padding-left: 30px;"><span id="span_id_lander_lieferung">weltweit;</span>.</p>
            <p>Bei einzelnen Sperrgutartikeln können die möglichen Lieferadressen sowie der Ablieferungsort beschränkt sein; die Beschränkung ist im jeweiligen Listenpreis ausgewiesen.</p>
            <p>(3) Der Besteller muss das 18. Lebensjahr vollendet haben.</p>
            <p>(4) Die Präsentation der Waren im Online-Shop stellt kein rechtlich wirksames Angebot dar. Durch die Präsentation der Ware wird der Kunde lediglich dazu aufgefordert ein Angebot zu machen.</p>
            <p>(5) Ihre Bestellung stellt ein Angebot an <span id="span_id_name_online_shop">Everbuild</span> zum Abschluss eines Kaufvertrages dar. Der Besteller gibt ein verbindliches Angebot ab, wenn er den Online-Bestellprozess unter Eingabe der dort verlangten Angaben durchlaufen hat und im letzten Bestellschritt den Button "kostenpflichtig bestellen" anklickt.</p>
            <p>(6) Der Kaufvertrag zwischen dem Anbieter und dem Besteller kommt erst durch eine Annahmeerklärung des Anbieters zustande. Diese erfolgt zum früheren der beiden Termine, entweder Zusendung der Ware oder Zusendung einer Versandbestätigung per E-Mail. Beachten Sie, dass die Bestätigung über den Eingang Ihrer Bestellung keine Annahmeerklärung im zuvor genannten Sinne darstellt.</p>
            <p>(7) Die Wirksamkeit von Verträgen über größere als haushaltsübliche Mengen sowie der gewerbliche Weiterverkauf des Kaufgegenstands bedarf der ausdrücklichen Bestätigung seitens des Anbieters. Dies bezieht sich sowohl auf die Anzahl der bestellten Produkte im Rahmen einer Bestellung als auch auf die Aufgabe mehrerer Bestellungen desselben Produkts, bei denen die einzelnen Bestellungen eine haushaltsübliche Menge umfassen.</p>
            <p>(8) Ihre Bestellungen werden bei uns nach Vertragsschluss gespeichert. Sollten Sie Ihre Unterlagen zu Ihren Bestellungen verlieren, wenden Sie sich bitte per E-Mail oder Telefon an uns. Wir senden Ihnen eine Kopie der Bestelldaten zu.</p>
            <p>(9) Der Zugang zur Nutzung des <span id="span_id_name_online_shop">Everbuild</span>-Service setzt die Anmeldung voraus.</p>
            <p>(10) Mit der Anmeldung erkennt der Besteller die vorliegenden AGB an. Mit der Anmeldung entsteht ein Vertragsverhältnis zwischen <span id="span_id_name_online_shop">Everbuild</span> und dem angemeldeten Besteller, das sich nach den Regelungen dieser AGB richtet.</p>
            <p>(11) Die Präsentation der Dienstleistung auf der Website stellt kein rechtlich wirksames Angebot dar. Durch die Präsentation der Dienstleistung wird der Kunde lediglich dazu aufgefordert ein Angebot zu machen.</p>
            <p>(12) Mit Bestellung eines kostenpflichtigen Dienstes geht der angemeldete Besteller ein weiteres, von der Anmeldung getrenntes Vertragsverhältnis mit <span id="span_id_name_online_shop">Everbuild</span> ein. Der Nutzer wird vor Abschluss dieses Vertragsverhältnisses über den jeweiligen kostenpflichtigen Dienst und die Zahlungsbedingungen informiert. Das Vertragsverhältnis entsteht indem der Besteller die Bestellung und Zahlungsverpflichtung durch das Anklicken des Buttons „<span id="span_id_bezeichnung_des_buttons_den_der_kunde_anklickt_um_seine_bestellung_zu_bestatigen">kostenpflichtig bestellen</span>" bestätigt.</p>
            <p>(13) Sie stimmen zu, dass Sie Rechnungen elektronisch erhalten. Elektronische Rechnungen werden Ihnen per E-Mail oder in dem Kundenkonto der Webseite zur Verfügung gestellt. Wir werden Sie für jede Lieferung und Dienstleistung   darüber informieren, ob eine elektronische Rechnung verfügbar ist. Weitere Informationen über elektronische Rechnungen erhalten Sie auf unserer Website.</p>
            <p style="text-align: left;"><br><strong>§ 3 </strong><strong>Beschreibung des Leistungsumfanges</strong></p>
            <p style="text-align: left;">Der Leistungsumfang von <span id="span_id_name_online_shop">Everbuild</span> besteht aus folgenden Dienstleistungen:</p>
            <p style="text-align: left; padding-left: 30px;"><span id="span_id_beschreiben_sie_hier_genau_den_leistungsumfang">Der Nutzer kann sich kostenlos registrieren und auch Zahlungspflichtige Produkte bestellen.</span></p>
            <p style="text-align: left;"><strong><br>§ 4 </strong><strong>Preise und Versandkosten</strong></p>
            <p style="text-align: left;">(1) Unsere Preise beinhalten die jeweils gültige gesetzliche Mehrwertsteuer und verstehen sich ohne Versandkostenpauschale oder Versandkostenzuschlag. Die Versandkostenzuschläge variieren je nach Lieferart und Artikelbeschaffenheit.</p>
            <p style="text-align: left;">(2) Trotz unserer größten Bemühungen kann eine kleine Anzahl der Produkte in unserem Katalog mit dem falschen Preis ausgezeichnet sein. Wir überprüfen die Preise, wenn wir Ihre Bestellung bearbeiten und bevor wir die Zahlung belasten. Wenn ein Produkt mit einem falschen Preis ausgezeichnet ist und der korrekte Preis höher ist, als der Preis auf der Webseite, werden wir Sie vor Versand der Ware kontaktieren, um Sie zu fragen, ob Sie das Produkt zum korrekten Preis kaufen oder die Bestellung stornieren möchten. Sollte der korrekte Preis eines Produkts niedriger sein, als der von uns angegebene Preis, werden wir den niedrigeren Betrag berechnen und Ihnen das Produkt zusenden.</p>
            <p style="text-align: left;">(3) Es gelten die Preise zum Zeitpunkt der Bestellung. Falls Listenpreise vorhanden sein sollten, gelten die Preise des zum Zeitpunkt der Bestellung gültigen Listenpreises.</p>
            <p style="text-align: left;">(4) Zur Nutzung von <span id="span_id_name_online_shop">Everbuild</span> ist zunächst eine Registrierung notwendig.</p>
            <p>(5) Um die Dienstleistungen der Website kaufen zu können, muss der Nutzer sich registrieren und ein Benutzerkonto erstellen.</p>
            <p>(6) Sofern der Nutzer einen kostenpflichtigen Dienst in Anspruch nehmen möchte, wird er vorher auf die Kostenpflichtigkeit hingewiesen. So werden ihm insbesondere der jeweilige zusätzliche Leistungsumfang, die anfallenden Kosten und die Zahlungsweise aufgeführt.</p>
            <p>(7) Der Anbieter behält sich das Recht vor, für verschiedene Buchungszeitpunkte und Nutzergruppen und insbesondere für verschiedene Nutzungszeiträume unterschiedliche Entgeltmodelle zu berechnen, wie auch verschiedene Leistungsumfänge anzubieten.</p>
            <p style="text-align: left;"><br><strong>§ 5 </strong><strong>Lieferung und Stornierung</strong></p>
            <p>(1) Sofern nicht anders vereinbart, erfolgt die Lieferung an die vom Besteller angegebene Lieferadresse. Auf der Webseite finden Sie Hinweise zur Verfügbarkeit von Produkten, die von <span id="span_id_name_online_shop">Everbuild</span> verkauft werden (z.B. auf der jeweiligen Produktdetailseite). Wir weisen darauf hin, dass sämtliche Angaben zu Verfügbarkeit, Versand oder Zustellung eines Produktes lediglich voraussichtliche Angaben und ungefähre Richtwerte sind. Sie stellen keine verbindlichen bzw. garantierten Versand- oder Liefertermine dar, außer wenn dies bei den Versandoptionen des jeweiligen Produktes ausdrücklich als verbindlicher Termin bezeichnet ist.</p>
            <p>(2) Sofern <span id="span_id_name_online_shop">Everbuild</span> während der Bearbeitung Ihrer Bestellung feststellt, dass von Ihnen bestellte Produkte nicht verfügbar sind, werden Sie darüber gesondert per E-Mail oder per Nachricht in Ihrem Kundenkonto informiert. Die gesetzlichen Ansprüche des Bestellers bleiben unberührt.</p>
            <p>(3) Soweit eine Lieferung an den Besteller nicht möglich ist, weil die gelieferte Ware nicht durch die Eingangstür, Haustür oder den Treppenaufgang des Bestellers passt oder weil der Besteller nicht unter der von ihm angegebenen Lieferadresse angetroffen wird, obwohl der Lieferzeitpunkt dem Besteller mit angemessener Frist angekündigt wurde, trägt der Besteller die Kosten für die erfolglose Anlieferung.</p>
            <p>(4) Die Lieferung erfolgt je nach Zahlungsart des Kunden. Bei Vorkasse erfolgt die Lieferung nach der Erteilung des Zahlungsauftrags an das überweisende Kreditinstitut. Bei Zahlung per Paypal, Kreditkarte, Geschenkkarte, Lastschrift, Sofortüberweisung oder Rechnung erfolgt die Lieferung nach Vertragsschluss.</p>
            <p>(5) Wenn Ihre Bestellung in mehr als einem Paket versendet wird, kann es vorkommen, dass Sie für jedes Paket eine eigene Versandbestätigung erhalten. In diesem Fall kommt bezüglich jeder Versandbestätigung ein separater Kaufvertrag zwischen uns über die in der jeweiligen Versandbestätigung aufgeführten Produkte zustande. Vertragspartner ist <span id="span_id_firma_mit_firmenzusatz">Everbuild</span>. Ungeachtet Ihres Widerrufsrechts können Sie Ihre Bestellung für ein Produkt vor Zusendung der zugehörigen Versandbestätigung jederzeit kostenfrei stornieren. </p>
            <p>(6) Dieses Recht zur Stornierung besteht nicht bei bestimmten Produktgruppen und Services, einschließlich digitaler Inhalte oder Software, die nicht auf einem körperlichen Datenträger (bspw. auf einer CD oder DVD) geliefert werden, sofern der Download oder die Nutzung (je nachdem, welches der frühere Zeitpunkt ist ) begonnen hat.</p>
            <p style="text-align: left;"><br><strong>§ 6 </strong><strong>Zoll</strong></p>
            <p>(1) Wenn Sie Produkte bei <span id="span_id_name_online_shop">Everbuild</span> zur Lieferung außerhalb der Europäischen Union bestellen, können Sie Importzöllen und -steuern unterliegen, die erhoben werden, sobald das Paket den bestimmten Zielort erreicht. Jegliche zusätzlichen Gebühren für die Zollabfertigung müssen von Ihnen getragen werden; wir haben keinen Einfluss auf diese Gebühren. Zollregelungen unterscheiden sich stark von Land zu Land, so dass Sie Ihre örtliche Zollbehörde für nähere Informationen kontaktieren sollten.</p>
            <p>(2) Ferner beachten Sie bitte, dass Sie bei Bestellungen bei <span id="span_id_name_online_shop">Everbuild</span> als Einführender angesehen werden und alle Gesetze und Verordnungen des Landes, in dem Sie die Produkte erhalten, einhalten müssen. Der Schutz Ihrer Daten ist wichtig für uns und wir möchten unsere internationalen Kunden darauf aufmerksam machen, dass grenzüberschreitende Lieferungen der Öffnung und Untersuchung durch Zollbehörden unterliegen. Für weitere Informationen lesen Sie bitte unsere Zollinformationen.</p>
            <p style="text-align: left;"><strong><br>§ 7 </strong><strong>Zahlungsbedingungen</strong></p>
            <p>(1) Ein anfallendes Entgelt ist im Voraus, zum Zeitpunkt der Fälligkeit ohne Abzug an <span id="span_id_name_online_shop">Everbuild</span> zu entrichten.</p>
            <p>(2) Mit der Anmeldung, der Angabe der für das Bezahlverfahren notwendigen Informationen sowie der Nutzung des kostenpflichtigen Dienstes erteilt der Nutzer dem Betreiber die Ermächtigung zum Einzug des entsprechenden Betrags.</p>
            <p>(3) Ein kostenpflichtiger Dienst verlängert sich um den jeweils gebuchten Zeitraum (Abonnement) automatisch, soweit dieser nicht per Telefon, E-Mail oder Brief gekündigt wird.</p>
            <p>(4) Das Abonnement wird zum folgenden Zeitpunkt eingezogen: <span id="span_id_zeitpunkt_einzug_abo">am ersten Werktag des Monats</span>.</p>
            <p>(5) Der Besteller kann die Ware oder Dienstleistung durch folgende Zahlungsarten bezahlen: </p>
            <p style="padding-left: 30px;">- Paypal</p>

            <p style="padding-left: 30px;">- Stripe</p>

            <p style="padding-left: 30px;">- Geschenkkarte</p>

            <p style="padding-left: 30px;">- Lastschrift:</p>
            <p>Im Falle einer vom Besteller zu vertretenden Rücklastschrift erhebt die <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> einen pauschalierten Schadensersatz in Höhe von <span id="span_id_lastschrift_ruck">0</span> € (null Euro). Der Besteller kann nachweisen, dass ein Schaden überhaupt nicht entstanden oder wesentlich niedriger ist als die Pauschale. Die vorstehenden Regelungen gelten entsprechend für Zahlungen des Kaufpreises von Waren, die von Drittanbietern verkauft werden.</p>
            <p style="padding-left: 30px;">- Sofortüberweisung</p>

            <p>(6) Bestimmte Zahlungsarten können im Einzelfall von dem Anbieter ausgeschlossen werden.</p>
            <p>(7) Dem Besteller ist nicht gestattet die Ware oder Dienstleistung durch das Senden von Bargeld oder Schecks zu bezahlen.</p>
            <p>(8) Sollte der Besteller ein Online-Zahlungsverfahren wählen, ermächtigt der Besteller den Anbieter dadurch, die fälligen Beträge zum Zeitpunkt der Bestellung einzuziehen.</p>
            <p>(9) Sollte der Anbieter die Bezahlung per Vorkasse anbieten und der Besteller diese Zahlungsart wählen, hat der Besteller den Rechnungsbetrag innerhalb von fünf Kalendertagen nach Eingang der Bestellung, auf das Konto des Anbieters zu überweisen. Der Anbieter reserviert die Ware dementsprechend für fünf Kalendertage.</p>
            <p>(10) Sollte der Anbieter die Bezahlung per Kreditkarte anbieten und der Besteller diese Zahlungsart wählen, ermächtigt dieser den Anbieter ausdrücklich dazu, die fälligen Beträge einzuziehen.</p>
            <p>(11) Sollte der Anbieter die Bezahlung per Lastschrift anbieten und der Besteller diese Zahlungsart wählen, erteilt der Besteller dem Anbieter ein SEPA Basismandat. Sollte es bei der Zahlung per Lastschrift zu einer Rückbuchung einer Zahlungstransaktion mangels Kontodeckung oder aufgrund falsch übermittelter Daten der Bankverbindung kommen, so hat der Besteller dafür die Kosten zu tragen.</p>
            <p>(12) Sollte der Anbieter die Bezahlung per Vorkasse anbieten und der Besteller diese Zahlungsart wählen, verpflichtet sich der Besteller, den Rechnungsbetrag innerhalb von 14 Tagen nach Warenversand, ohne jeglichen Abzug von Skonto zu begleichen.</p>
            <p>(13) Sollte der Besteller mit der Zahlung in Verzug kommen, so behält sich der Anbieter die Geltendmachung des Verzugschadens vor.</p>
            <p style="text-align: left;"><strong><br>§ 8 </strong><strong>Anmeldung und Kündigung</strong></p>
            <p style="text-align: left;">(1) Weiterhin erklärt der Besteller, dass er und nach seiner Kenntnis auch kein Mitglied seines Haushaltes nicht wegen einer vorsätzlichen Straftat die die Sicherheit von Dritten gefährdet vorbestraft ist, insbesondere nicht wegen einer Straftat gegen die sexuelle Selbstbestimmung (§§ 174 ff. StGB, einer Straftat gegen das Leben (§§ 211 ff. StGB), einer Straftat gegen die körperliche Unversehrtheit (§ 223 ff. StGB), einer Straftat gegen die persönliche Freiheit (§§ 232 ff. StGB), oder wegen eines Diebstahl und Unterschlagung (§§ 242 ff. StGB) oder des Raubes und der Erpressung (§§ 249 ff. StGB) oder wegen Drogenmissbrauch.</p>
            <p>(2) Ein Nutzerkonto ist für seine/ihre alleinige und persönliche Nutzung und ein Nutzer darf Dritte nicht autorisieren dieses Konto zu nutzen. Ein Nutzer darf sein/ ihr Konto nicht an Dritte übertragen.</p>
            <p>(3) Ein Nutzer ist, unter Vorbehalt, jederzeit berechtigt, sich ohne Angabe eines Grundes schriftlich per Post, E-Mail oder Telefon abzumelden. Gleichzeitig besteht bei die Möglichkeit, innerhalb der Daten und Einstellungen im Nutzer-Account diesen vollständig und eigenhändig zu deaktivieren. Das vorher geschlossene Vertragsverhältnis ist damit beendet.</p>
            <p>(4) Hat ein Nutzer sich für einen entgeltlichen Dienst angemeldet, so kann er spätestens  <span id="span_id_kundigungsfrist_abo">90</span> Tage vor dem Buchungszeitraum kündigen. Wird diese Frist nicht eingehalten, so verlängert sich der kostenpflichtige Dienst je nach gewählter Buchungszeit um diese und die Kündigung wird erst zum Ende des Folgebuchungszeitraumes wirksam. Eine Kündigung ist per Telefon, E-Mail oder Brief möglich und wird von uns schriftlich bestätigt. Damit Ihre Kündigung zugeordnet werden kann sollen der vollständige Name, die hinterlegte E-Mail-Adresse und die Anschrift des Kunden angegeben werden. Im Fall einer Kündigung per Telefon wird das individuelle Telefon-Passwort benötigt.</p>
            <p>(5) <span id="span_id_name_online_shop">Everbuild</span> kann den Vertrag nach eigenem Ermessen, mit oder ohne vorherige Ankündigung und ohne Angabe von Gründen, zu jeder Zeit kündigen. <span id="span_id_name_online_shop">Everbuild</span> hält sich weiterhin das Recht vor, Profile und /oder jeden Inhalt der auf der Website durch oder von dem Nutzer veröffentlich wurde zu entfernen. Falls <span id="span_id_name_online_shop">Everbuild</span> die Registrierung des Nutzers beendet und/oder Profile oder veröffentliche Inhalte des Nutzers entfernt, besteht für <span id="span_id_name_online_shop">Everbuild</span> keine Verpflichtung den Nutzer darüber noch über den Grund der Beendigung oder der Entfernung zu informieren.</p>
            <p>(6) Im Anschluss an jede Beendigung von jedweder individuellen Nutzung der Services von <span id="span_id_name_online_shop">Everbuild</span>, hält <span id="span_id_name_online_shop">Everbuild</span> sich das Recht vor, eine Information hierüber an andere registrierte Nutzer mit denen <span id="span_id_name_online_shop">Everbuild</span> annimmt, dass diese in Kontakt mit dem Nutzer standen, zu versenden. <span id="span_id_name_online_shop">Everbuild</span>'s Entscheidung die Registrierung des Nutzers zu beenden und/oder weitere Nutzer zu benachrichtigen mit dem <span id="span_id_name_online_shop">Everbuild</span> annimmt, dass der Nutzer in Kontakt stand, impliziert nicht bzw. sagt keinesfalls aus, dass <span id="span_id_name_online_shop">Everbuild</span> Aussagen über den individuellen Charakter, generelle Reputation, persönliche Charakteristika noch über den Lebensstil trifft.</p>
            <p>(7) Die Nutzer sind verpflichtet, in Ihrem Profil und sonstigen Bereichen des Portals keine absichtlichen oder betrügerischen Falschangaben zu machen. Solche Angaben können zivilrechtliche Schritte nach sich ziehen. Der Betreiber behält sich darüber hinaus das Recht vor, in einem solchen Fall das bestehende Vertragsverhältnis mit sofortiger Wirkung aufzulösen.</p>
            <p>(8) Wird der Zugang eines Nutzers wegen schuldhaften Vertragsverstoßes gesperrt und/oder das Vertragsverhältnis aufgelöst, hat der Nutzer für die verbleibende Vertragslaufzeit Schadenersatz in Höhe des vereinbarten Entgelts abzüglich der ersparten Aufwendungenzu zahlen. Die Höhe der ersparten Aufwendungen wird pauschal auf 10% des Entgelts angesetzt. Es bleibt beiden Vertragsparteien unbenommen nachzuweisen, dass der Schaden, und/oder die ersparten Aufwendungen tatsächlich höher oder niedriger sind.</p>
            <p>(9) Nach Beendigung des Vertragsverhältnisses werden sämtliche Daten des Nutzers von <span id="span_id_name_online_shop">Everbuild</span> gelöscht.</p>
            <p style="text-align: left;"><strong><br>§ 9 </strong><strong>Haftungsbegrenzung (Dienstleistungen)</strong></p>
            <p style="text-align: left;">(1) <span id="span_id_name_online_shop">Everbuild</span> übernimmt keine Verantwortung für den Inhalt und die Richtigkeit der Angaben in den Anmelde- und Profildaten der Besteller sowie weiteren von den Bestellern generierten Inhalten.</p>
            <p style="text-align: left;">(2) In Bezug auf die gesuchte oder angebotene Dienstleistung kommt der Vertrag ausschließlich zwischen den jeweilig beteiligten Bestellern zustande. Daher haftet <span id="span_id_name_online_shop">Everbuild</span> nicht für Leistungen der teilnehmenden Besteller. Entsprechend sind alle Angelegenheiten bzgl. der Beziehung zwischen den Bestellern einschließlich, und ohne Ausnahme, der Dienstleistungen die ein Suchender erhalten hat oder Zahlungen die an Besteller fällig sind, direkt an die jeweilige Partei des zu richten. <span id="span_id_name_online_shop">Everbuild</span> kann hierfür nicht verantwortlich gemacht werden und widerspricht hiermit ausdrücklich allen etwaigen Haftungsansprüchen welcher Art auch immer einschließlich Forderungen, Leistungen, direkte oder indirekte Beschädigungen jeder Art, bewusst oder unbewusst, vermutet oder unvermutet, offengelegt oder nicht, in welcher Art auch immer im Zusammenhang mit den genannten Angelegenheiten.</p>
            <p style="text-align: left;">(3) Für Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit haftet <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> nur, wenn sie auf einer vorsätzlichen oder fahrlässigen Pflichtverletzung von <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> oder einer vorsätzlichen oder fahrlässigen Pflichtverletzung eines gesetzlichen Vertreters oder Erfüllungsgehilfen von <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> beruhen.</p>
            <p style="text-align: left;">(4) Für sonstige Schäden, soweit sie nicht auf der Verletzung von Kardinalpflichten (solche Pflichten, deren Erfüllung die ordnungsgemäße Durchführung des Vertrages überhaupt erst ermöglichen und auf deren Einhaltung der Vertragspartner regelmäßig vertrauen darf) beruhen, haftet <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> Europe nur, wenn sie auf einer vorsätzlichen oder grob fahrlässigen Pflichtverletzung von <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> oder auf einer vorsätzlichen oder grob fahrlässigen Pflichtverletzung eines gesetzlichen Vertreters oder Erfüllungsgehilfen von <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> beruhen.</p>
            <p style="text-align: left;">(5) Die Schadensersatzansprüche sind, auf den vorhersehbaren, vertragstypischen Schaden begrenzt. Sie betragen im Falle des Verzuges höchstens 5% des Auftragswertes.</p>
            <p style="text-align: left;">(6) Schadenersatzansprüche, die auf der Verletzung des Lebens, des Körpers oder der Gesundheit oder der Freiheit beruhen, verjähren nach 30 Jahren; im Übrigen nach 1 Jahr, wobei die Verjährung mit dem Schluss des Jahres, in dem der Anspruch entstanden ist und der Gläubiger von den Anspruch begründenden Umständen und der Person des Schuldners Kenntnis erlangt oder ohne grobe Fahrlässigkeit erlangen müsste (§ 199 Abs.1 BGB).</p>
            <p style="text-align: left;">(7) Der Anbieter behält sich das Recht vor, den Inhalt eines von einem Nutzer verfassten Textes sowie hochgeladener Dateien auf die Einhaltung von Gesetz und Recht hin zu überprüfen und, wenn nötig, ganz oder teilweise zu löschen.</p>
            <p style="text-align: left;"><strong><br>§ 10 </strong><strong>Aufrechnung und Zurückbehaltungsrecht</strong></p>
            <p>(1) Dem Besteller steht das Recht zur Aufrechnung nur zu, wenn die Gegenforderung des Bestellers rechtskräftig festgestellt worden ist oder von dem Anbieter nicht bestritten wurde.</p>
            <p>(2) Der Besteller kann ein Zurückbehaltungsrecht nur ausüben, soweit Ihre Gegenforderung auf demselben Vertragsverhältnis beruht.</p>
            <p style="text-align: left;"><strong><br>§ 11 </strong><strong>Eigentumsvorbehalt</strong></p>
            <p style="text-align: left;"><span id="span_id_firma_mit_firmenzusatz">Everbuild</span> behält sich das Eigentum an der Ware bis zur vollständigen Bezahlung vor.</p>
            <p style="text-align: left;"><strong><br>§ 12 </strong><strong>Mängelrecht</strong></p>
            <p style="text-align: left;">(1) Ist der Besteller ein Verbraucher, so richtet sich die Gewährleistung und Mängelhaftung des gelieferten Kaufgegenstandes nach den gesetzlichen Vorschriften: Demnach haben Besteller in der Europäischen Union zusätzlich zu Ihrer 30-Tage Rückgabegarantie für einen Zeitraum von zwei Jahren ab der Lieferung der Ware Gewährleistungsrechte und können die Reparatur oder den Ersatz der auf <span id="span_id_name_online_shop">Everbuild</span> gekauften Produkte verlangen, wenn diese sich als mangelhaft oder nicht wie beschrieben erweisen. Wenn die Ware nicht innerhalb einer angemessenen Zeit oder nicht ohne Schwierigkeiten repariert oder ersetzt werden kann, können Sie die Rückerstattung oder Minderung des Kaufpreises verlangen.</p>
            <p style="text-align: left;">(2) Im Fall von gebrauchten Waren kann die Gewährleistungsfrist kürzer als zwei Jahre sein.</p>
            <p style="text-align: left;">(3) Ist der Besteller kein Verbraucher, so wird der Mangel durch Neulieferung oder Neuerfüllung beseitigt. </p>
            <p style="text-align: left;">(4) Ist der Besteller kein Verbraucher so beträgt die Verjährungsfrist ein Jahr. Dies gilt soweit keine Schadens- und Aufwendungsersatzansprüche, die sich auf Ersatz eines Schadens in Bezug auf Körper und Gesundheit oder auf Vorsatz oder grobe Fahrlässigkeit geltend gemacht werden.</p>
            <p style="text-align: left;"><strong><br>§ 13 </strong><strong>Haftungsbegrenzung (Produkte)</strong></p>
            <p style="text-align: left;">(1) Der Anbieter haftet für Schadensersatzansprüche des Bestellers aus der Verletzung des Lebens, des Körpers, der Gesundheit oder aus der Verletzung wesentlicher Vertragspflichten, sowie für sonstige Schäden, die auf ihrer vorsätzlichen oder grob fahrlässigen Pflichtverletzung, oder einer der gesetzlichen Vertreter oder Erfüllungsgehilfen des Anbieters beruhen.</p>
            <p style="text-align: left;">(2) Als wesentliche Vertragspflichten, gelten Pflichten deren Erfüllung zur Erreichung des Ziels des Vertrags notwendig ist.</p>
            <p style="text-align: left;">(3) Der Anbieter haftet für Verletzungen wesentlicher Vertragspflichten, die auf vertragstypischen, vorhersehbaren Schäden beruhen, vorausgesetzt der Schaden wurde einfach fahrlässig verursacht. Diese Begrenzung gilt nicht für Schadensersatzansprüche des Bestellers, die auf einer Verletzung des Lebens, des Körpers oder der Gesundheit beruhen.</p>
            <p style="text-align: left;">(4) Die Vorschriften des Produkthaftungsgesetzes bleiben unberührt.</p>
            <p style="text-align: left;">(5) Soweit die Haftung von <span id="span_id_name_online_shop">Everbuild</span> ausgeschlossen oder beschränkt ist, gilt dies auch für die persönliche Haftung von Arbeitnehmern, Vertretern und Erfüllungsgehilfen.</p>
            <p style="text-align: left;"><strong><br>§ 14 </strong><strong>Widerrufsbelehrung</strong></p>
            <p>(1) Ist der Besteller ein Verbraucher, so hat er ein Widerrufsrecht nach Maßgabe der folgenden Bestimmungen:</p>
            <p>(2) Widerrufsrecht</p>
            <p>Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.</p>
            <p>Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Ware (oder die letzte Ware, Teilsendung oder Stück im Falle eines Vertrags über mehrere Waren einer einheitlichen Bestellung oder die Lieferung einer Ware in mehreren Teilsendungen oder Stücken) in Besitz genommen haben oder ab dem Tag des Vertragsschlusses, im Falle von digitalen Inhalten, die nicht auf einem körperlichen Datenträger geliefert werden (z.B. CDs oder DVDs), ohne Angabe von Gründen zu widerrufen.</p>
            <p>Die Widerrufsfrist für Dienstleistungen beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses.</p>
            <p>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns:</p>
            <p><span id="span_id_firma_mit_firmenzusatz">Everbuild</span></p>
            <p><span id="span_id_adresse_firma">Fallerweg 7<br>54516 Wittlich<br>Deutschland</span> </p>
            <p>E-Mail: <span id="span_id_e_mail_firma">nico.weber24@gmx.de</span></p>
            <p>mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das Muster-Widerrufsformular auf unserer Internetseite verwenden oder uns eine andere eindeutige Erklärung übermitteln. Machen Sie von dieser Möglichkeit Gebrauch, so werden wir Ihnen unverzüglich (z.B. per E-Mail) eine Bestätigung über den Eingang eines solchen Widerrufs übermitteln.</p>
            <p>Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden und Sie die Waren über unser Online-Rücksendezentrum innerhalb der unten definierten Frist zurückgesendet haben.</p>
            <p>Für zusätzliche Informationen hinsichtlich der Reichweite, des Inhalts und Erläuterungen zur Ausübung wenden Sie sich bitte an unseren Kundenservice.</p>
            <p>(3) Folgen des Widerrufs</p>
            <p>Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen 14 Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.</p>
            <p>Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen sollen, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht.</p>
            <p>Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.</p>
            <p>Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen 14 Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrags unterrichten, an</p>
            <p><span id="span_id_firma_mit_firmenzusatz">Everbuild</span></p>
            <p><span id="span_id_adresse_firma">Fallerweg 7<br>54516 Wittlich<br>Deutschland</span> </p>
            <p>E-Mail: <span id="span_id_e_mail_firma">nico.weber24@gmx.de</span></p>
            <p>zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von 14 Tagen absenden. Sie haben die regelmäßigen Kosten der Rücksendung zu tragen, wenn die gelieferte Ware der bestellten entspricht und wenn der Preis der zurückzusendenden Sache einen Betrag von <span id="span_id_ab_welchem_betrag_ubernimmt_der_anbieter_lieferkosten">0</span> € (null Euro) nicht übersteigt oder wenn Sie bei einem höheren Preis der Sache zum Zeitpunkt des Widerrufs noch nicht die Gegenleistung oder eine vertraglich vereinbarte Teilzahlung erbracht haben. Andernfalls ist die Rücksendung für Sie kostenfrei. </p>
            <p>(4) Ausnahmen vom Widerrufsrecht</p>
            <p>Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.</p>
            <p>Das Widerrufsrecht besteht nicht bzw. erlischt bei folgenden Verträgen:</p>
            <ul>
                <li>zur Lieferung von Waren, die aus Gründen des Gesundheitsschutzes oder aus Hygienegründen nicht zur Rückgabe geeignet sind und deren Versiegelung nach der Lieferung entfernt wurde oder die nach der Lieferung aufgrund ihrer Beschaffenheit untrennbar mit anderen Gütern vermischt wurden;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Ton- oder Videoaufnahmen oder Computersoftware in einer versiegelten Packung, wenn die Versiegelung nach der Lieferung entfernt wurde;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Waren, die nach Kundenspezifikation angefertigt werden oder eindeutig auf die persönlichen Bedürfnisse zugeschnitten sind</li>
            </ul>
            <ul>
                <li>zur Lieferung von Waren, die schnell verderben können oder deren Verfallsdatum schnell überschritten würde;</li>
            </ul>
            <ul>
                <li>bei Dienstleistungen, wenn <span id="span_id_name_online_shop">Everbuild</span> diese vollständig erbracht hat und Sie vor der Bestellung zur Kenntnis genommen und ausdrücklich zugestimmt haben, dass wir mit der Erbringung der Dienstleistung beginnen können und Sie Ihr Widerrufsrecht bei vollständiger Vertragserfüllung verlieren;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Zeitungen, Zeitschriften oder Illustrierte, mit Ausnahme von Abonnement-Verträgen; und</li>
            </ul>
            <ul>
                <li>zur Lieferung alkoholischer Getränke, deren Preis beim Abschluss des Kaufvertrags vereinbart wurde, deren Lieferung aber erst nach 30 Tagen erfolgen kann und deren aktueller Wert von Schwankungen auf dem Markt abhängt, auf die der Unternehmer keinen Einfluss hat.</li>
            </ul>

            <p style="text-align: left;"><strong><br>§ 15 </strong><strong>Ausschluss des Widerrufsrechts</strong></p>
            <p style="text-align: left;">(1) Das Widerrufsrecht besteht nicht bei Verträgen</p>
            <ul>
                <li>zur Lieferung von Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher maßgeblich ist oder die eindeutig auf die persönlichen Bedürfnisse des Verbrauchers zugeschnitten sind;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Waren, die schnell verderben können oder deren Verfallsdatum schnell überschritten würde;</li>
            </ul>
            <p style="text-align: left;">(2) Das Widerrufsrecht erlischt vorzeitig bei Verträgen</p>
            <ul>
                <li>zur Lieferung versiegelter Waren, die aus Gründen des Gesundheitsschutzes oder der Hygiene nicht zur Rückgabe geeignet sind, wenn ihre Versiegelung nach der Lieferung entfernt wurde;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Waren, wenn diese nach der Lieferung auf Grund ihrer Beschaffenheit untrennbar mit anderen Gütern vermischt wurden;</li>
            </ul>
            <ul>
                <li>zur Lieferung von Ton- oder Videoaufnahmen oder Computersoftware in einer versiegelter Packung, wenn die Versiegelung nach der Lieferung entfernt wurde.</li>
            </ul>
            <p style="text-align: left;"><br><strong>§ 16 </strong><strong>Datenschutz</strong></p>
            <p>(1) Sollten personenbezogene Daten (z.B. Name, Anschrift, E-Mail-Adresse) erhoben werden, verpflichten wir uns dazu, Ihre vorherige Einverständnis einzuholen. Wir verpflichten uns dazu, keine Daten an Dritte weiterzugeben, es sei denn, Sie haben zuvor eingewilligt.</p>
            <p>(2) Wir weisen darauf hin, dass die Übertragung von Daten im Internet (z. B. per E-Mail) Sicherheitslücken aufweisen kann. Demnach kann ein fehlerfreier und störungsfreier Schutz der Daten Dritter nicht vollständig gewährleistet werden. Diesbezüglich ist unsere Haftung ausgeschlossen.</p>
            <p>(3) Dritte sind nicht dazu berechtigt, Kontaktdaten für gewerbliche Aktivitäten zu nutzen, sofern der Anbieter den betroffenen Personen vorher eine schriftliche Einwilligung erteilt hat.</p>
            <p>(4) Sie haben jederzeit das Recht, von <span id="span_id_name_online_shop">Everbuild</span> über den Sie betreffenden Datenbestand vollständig und unentgeltlich Auskunft zu erhalten.</p>
            <p>(5) Des Weiteren besteht ein Recht auf Berichtigung/Löschung von Daten/Einschränkung der Verarbeitung für den Nutzer.</p>
            <p>(6) Weitere Angaben zum Datenschutz sind in der separaten Datenschutzerklärung zu finden.</p>
            <p style="text-align: left;"><br><strong>§ 17 </strong><strong>Cookies</strong></p>
            <p>(1) Zur Anzeige des Produktangebotes kann es vorkommen, dass wir Cookies einsetzen. Bei Cookies handelt es sich um kleine Textdateien, die lokal im Zwischenspeicher des Internet-Browsers des Seitenbesuchers gespeichert werden.</p>
            <p>(2) Zahlreiche Internetseiten und Server verwenden Cookies. Viele Cookies enthalten eine sogenannte Cookie-ID. Eine Cookie-ID ist eine eindeutige Kennung des Cookies. Sie besteht aus einer Zeichenfolge, durch welche Internetseiten und Server dem konkreten Internetbrowser zugeordnet werden können, in dem das Cookie gespeichert wurde. Dies ermöglicht es den besuchten Internetseiten und Servern, den individuellen Browser der betroffenen Person von anderen Internetbrowsern, die andere Cookies enthalten, zu unterscheiden. Ein bestimmter Internetbrowser kann über die eindeutige Cookie-ID wiedererkannt und identifiziert werden.</p>
            <p>(3) Durch den Einsatz von Cookies kann den Nutzern dieser Internetseite nutzerfreundlichere Services bereitstellen, die ohne die Cookie-Setzung nicht möglich wären.</p>
            <p>(4) Wir weisen Sie darauf hin, dass einige dieser Cookies von unserem Server auf Ihr Computersystem überspielt werden, wobei es sich dabei meist um so genannte sitzungsbezogene Cookies handelt. Sitzungsbezogene Cookies zeichnen sich dadurch aus, dass diese automatisch nach Ende der Browser-Sitzung wieder von Ihrer Festplatte gelöscht werden. Andere Cookies verbleiben auf Ihrem Computersystem und ermöglichen es uns, Ihr Computersystem bei Ihrem nächsten Besuch wieder zu erkennen (sog. dauerhafte Cookies).</p>
            <p>(5) Sie können der Speicherung von Cookies widersprechen, hierzu steht Ihnen ein Banner zu Verfügung dem Sie widersprechen/annehmen können.</p>
            <p>(6) Selbstverständlich können Sie Ihren Browser so einstellen, dass keine Cookies auf der Festplatte abgelegt werden bzw. bereits abgelegte Cookies wieder gelöscht werden. Die Anweisungen bezüglich der Verhinderung sowie Löschung von Cookies können Sie der Hilfefunktion Ihres Browsers oder Softwareherstellers entnehmen.</p>
            <p style="text-align: left;"><strong><br>§ 18 </strong><strong>Schlussbestimmungen</strong></p>
            <p style="text-align: left;">(1) Vertragssprache ist deutsch und englisch.</p>
            <p>(2) Wir bieten keine Produkte oder Dienstleistungen zum Kauf durch Minderjährige an. Unsere Produkte für Kinder können nur von Erwachsenen gekauft werden. Falls Sie unter 18 sind, dürfen Sie <span id="span_id_name_online_shop">Everbuild</span> nur unter Mitwirkung eines Elternteils oder Erziehungsberechtigten nutzen.</p>
            <p>(3) Wenn Sie diese AGB verletzen und wir unternehmen hiergegen nichts, sind wir weiterhin berechtigt, von unseren Rechten bei jeder anderen Gelegenheit, in der Sie diese Verkaufsbedingungen verletzen, Gebrauch zu machen.</p>
            <p style="text-align: left;">(4) Wir behalten uns das Recht vor, Änderungen an unserer Webseite, Regelwerken, Bedingungen einschließlich dieser AGB jederzeit vorzunehmen. Auf Ihre Bestellung finden jeweils die Verkaufsbedingungen, Vertragsbedingungen und AGB Anwendung, die zu dem Zeitpunkt Ihrer Bestellung in Kraft sind, es sei denn eine Änderung an diesen Bedingungen ist gesetzlich oder auf behördliche Anordnung erforderlich (in diesem Fall finden sie auch auf Bestellungen Anwendung, die Sie zuvor getätigt haben). Falls eine Regelung in diesen Verkaufsbedingungen unwirksam, nichtig oder aus irgendeinem Grund undurchsetzbar ist, gilt diese Regelung als trennbar und beeinflusst die Gültigkeit und Durchsetzbarkeit der verbleibenden Regelungen nicht.</p>
            <p style="text-align: left;">(5) Die Unwirksamkeit einer Bestimmung berührt die Wirksamkeit der anderen Bestimmungen aus dem Vertrag nicht. Sollte dieser Fall eintreten, soll die Bestimmung nach Sinn und Zweck durch eine andere rechtlich zulässige Bestimmung ersetzt werden, die dem Sinn und Zweck der unwirksamen Bestimmung entspricht.</p>
            <p> Stand: 07.04.2024</p>
        {:else}
            <p style="text-align: center;"><strong>GENERAL TERMS AND CONDITIONS OF</strong></p>
            <p style="text-align: center;"><strong><em style="text-align: left;"><span id="span_id_url_interneteite">https://Everbuild.org</span></em></strong></p>
            <p style="text-align: left;"><em><br>Welcome to <span id="span_id_name_online_shop">Everbuild</span>!</em></p>

            <p style="text-align: left;"><strong><br>§ 1 </strong><strong>Scope and Provider</strong></p>
            <p>(1) The General Terms and Conditions (hereinafter referred to as "GTC") govern the sale of products and services by <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> (hereinafter referred to as the Provider) to you in their version valid at the time of ordering.</p>
            <p style="text-align: left;">(2) Deviating terms and conditions of the purchaser are rejected.</p>
            <p>(3) Please read these terms carefully before placing an order with <span id="span_id_firma_mit_firmenzusatz">Everbuild</span>. By placing an order with <span id="span_id_firma_mit_firmenzusatz">Everbuild</span>, you agree to be bound by these GTC.</p>
            <p>(4) At <span id="span_id_name_online_shop">Everbuild</span>, we offer you the sale of the following products:</p>
            <p style="padding-left: 30px;"><span id="span_id_produkte_beschreiben_hier">Online software</span></p>
            <p>(5) At <span id="span_id_name_online_shop">Everbuild</span>, we offer you the following services:</p>
            <p style="padding-left: 30px;"><span id="span_id_dienstleistungen_beschreiben_hier">Order development</span></p>
            <p style="text-align: left;"><strong><br>§ 2 </strong><strong>Conclusion of the Contract</strong></p>
            <p>(1) Contracts on this portal can only be concluded in German and English.</p>
            <p>(2) The offers are exclusively directed at end customers with an invoice and delivery address in:</p>
            <p style="padding-left: 30px;"><span id="span_id_lander_lieferung">worldwide;</span>.</p>
            <p>For individual bulky items, the possible delivery addresses and the place of delivery may be restricted; the restriction is indicated in the respective list price.</p>
            <p>(3) The purchaser must have reached the age of 18.</p>
            <p>(4) The presentation of goods in the online shop does not constitute a legally effective offer. The presentation of the goods merely prompts the customer to make an offer.</p>
            <p>(5) Your order constitutes an offer to <span id="span_id_name_online_shop">Everbuild</span> to conclude a purchase contract. The purchaser makes a binding offer when he has completed the online ordering process by entering the required information there and clicks the "order with obligation to pay" button in the last order step.</p>
            <p>(6) The purchase contract between the provider and the purchaser is only concluded by a declaration of acceptance by the provider. This takes place at the earlier of the two dates, either dispatch of the goods or dispatch of a shipping confirmation by e-mail. Please note that the confirmation of receipt of your order does not constitute a declaration of acceptance in the sense mentioned above.</p>
            <p>(7) The effectiveness of contracts for larger than household quantities as well as the commercial resale of the purchased item requires the express confirmation by the provider. This applies both to the number of ordered products within the framework of one order and to the placement of several orders for the same product, each of which comprises a household quantity.</p>
            <p>(8) Your orders are stored with us after the conclusion of the contract. If you lose your documents relating to your orders, please contact us by e-mail or telephone. We will send you a copy of the order data.</p>
            <p>(9) Access to the use of the <span id="span_id_name_online_shop">Everbuild</span> service requires registration.</p>
            <p>(10) By registering, the purchaser acknowledges the present GTC. By registering, a contractual relationship is established between <span id="span_id_name_online_shop">Everbuild</span> and the registered purchaser, which is governed by the provisions of these GTC.</p>
            <p>(11) The presentation of the service on the website does not constitute a legally effective offer. The presentation of the service merely prompts the customer to make an offer.</p>
            <p>(12) By ordering a paid service, the registered purchaser enters into another contractual relationship with <span id="span_id_name_online_shop">Everbuild</span> separate from the registration. The user will be informed about the respective paid service and the payment conditions before concluding this contractual relationship. The contractual relationship arises when the purchaser confirms the order and payment obligation by clicking the "order with obligation to pay" button.</p>
            <p>(13) You agree to receive invoices electronically. Electronic invoices will be provided to you by e-mail or in the customer account on the website. We will inform you for each delivery and service whether an electronic invoice is available. Further information on electronic invoices can be found on our website.</p>
            <p style="text-align: left;"><br><strong>§ 3 </strong><strong>Description of the Scope of Services</strong></p>
            <p style="text-align: left;">The scope of services of <span id="span_id_name_online_shop">Everbuild</span> consists of the following services:</p>
            <p style="text-align: left; padding-left: 30px;"><span id="span_id_beschreiben_sie_hier_genau_den_leistungsumfang">The user can register for free and also order paid products.</span></p>
            <p style="text-align: left;"><strong><br>§ 4 </strong><strong>Prices and Shipping Costs</strong></p>
            <p style="text-align: left;">(1) Our prices include the respective statutory value-added tax and do not include a flat-rate shipping fee or additional shipping surcharge. The shipping surcharges vary depending on the type of delivery and the nature of the item.</p>
            <p style="text-align: left;">(2) Despite our greatest efforts, a small number of products in our catalog may be incorrectly priced. We will check the prices when we process your order and before charging the payment. If a product is incorrectly priced and the correct price is higher than the price on the website, we will contact you before shipping the goods to ask if you would like to purchase the product at the correct price or cancel the order. If the correct price of a product is lower than the price stated by us, we will charge the lower amount and send you the product.</p>
            <p style="text-align: left;">(3) The prices at the time of ordering shall apply. If list prices are available, the prices of the list price valid at the time of ordering shall apply.</p>
            <p style="text-align: left;">(4) Registration is initially required to use <span id="span_id_name_online_shop">Everbuild</span>.</p>
            <p>(5) In order to purchase the services of the website, the user must register and create a user account.</p>
            <p>(6) If the user wishes to use a paid service, he will be informed in advance about the cost. In particular, the respective additional scope of services, the costs incurred and the payment method are listed.</p>
            <p>(7) The provider reserves the right to charge different fee models for different booking periods and user groups, and in particular to offer different scope of services.</p>
            <p style="text-align: left;"><br><strong>§ 5 </strong><strong>Delivery and Cancellation</strong></p>
            <p>(1) Unless otherwise agreed, delivery will be made to the delivery address specified by the purchaser. On the website, you will find information about the availability of products sold by <span id="span_id_name_online_shop">Everbuild</span> (e.g., on the respective product detail page). We would like to point out that all information on availability, shipping or delivery of a product is only approximate and approximate guidelines. They do not constitute binding or guaranteed shipping or delivery dates, unless expressly stated as binding dates in the shipping options of the respective product.</p>
            <p>(2) If <span id="span_id_name_online_shop">Everbuild</span> determines during the processing of your order that products ordered by you are not available, you will be separately informed by e-mail or by message in your customer account. The purchaser's statutory rights remain unaffected.</p>
            <p>(3) Insofar as delivery to the purchaser is not possible because the delivered goods do not fit through the entrance door, front door or stairway of the purchaser or because the purchaser is not encountered at the delivery address specified by him, although the delivery time has been announced to the purchaser with reasonable notice, the purchaser shall bear the costs for the unsuccessful delivery.</p>
            <p>(4) Delivery depends on the customer's payment method. In the case of advance payment, delivery will be made after the payment order has been issued to the transferring credit institution. In the case of payment by Paypal, credit card, gift card, direct debit, instant bank transfer or invoice, delivery will be made after conclusion of the contract.</p>
            <p>(5) If your order is shipped in more than one package, you may receive a separate shipping confirmation for each package. In this case, a separate purchase contract between us for the products listed in each shipping confirmation is concluded. The contracting party is <span id="span_id_firma_mit_firmenzusatz">Everbuild</span>. Regardless of your right of withdrawal, you can cancel your order for a product free of charge at any time before the associated shipping confirmation is sent. </p>
            <p>(6) This right of cancellation does not apply to certain product groups and services, including digital content or software that is not delivered on a physical medium (e.g., on a CD or DVD), if downloading or use (whichever is earlier) has begun.</p>
            <p style="text-align: left;"><br><strong>§ 6 </strong><strong>Customs</strong></p>
            <p>(1) If you order products from <span id="span_id_name_online_shop">Everbuild</span> for delivery outside the European Union, you may be subject to import duties and taxes, which are levied once the package reaches the specified destination. Any additional charges for customs clearance must be borne by you; we have no control over these charges. Customs regulations vary greatly from country to country, so you should contact your local customs office for further information.</p>
            <p>(2) Furthermore, please note that when ordering from <span id="span_id_name_online_shop">Everbuild</span>, you are considered the importer of record and must comply with all laws and regulations of the country in which you receive the products. The protection of your data is important to us and we would like to inform our international customers that cross-border deliveries are subject to opening and inspection by customs authorities. For further information, please read our customs information.</p>
            <p style="text-align: left;"><strong><br>§ 7 </strong><strong>Payment Terms</strong></p>
            <p>(1) Any fee is to be paid in advance, without deduction, to <span id="span_id_name_online_shop">Everbuild</span> at the time of maturity.</p>
            <p>(2) By registering, providing the necessary information for the payment process and using the paid service, the user authorizes the operator to collect the corresponding amount.</p>
            <p>(3) A paid service is automatically extended by the respective booked period (subscription), unless it is canceled by telephone, e-mail or letter.</p>
            <p>(4) The subscription will be debited on the following date: <span id="span_id_zeitpunkt_einzug_abo">on the first working day of the month</span>.</p>
            <p>(5) The purchaser can pay for the goods or services by the following payment methods: </p>
            <p style="padding-left: 30px;">- Paypal</p>

            <p style="padding-left: 30px;">- Stripe</p>

            <p style="padding-left: 30px;">- Gift card</p>

            <p style="padding-left: 30px;">- Direct debit:</p>
            <p>In the event of a chargeback caused by the purchaser, <span id="span_id_firma_mit_firmenzusatz">Everbuild</span> will charge a lump sum compensation of <span id="span_id_lastschrift_ruck">0</span> € (zero euros). The purchaser can demonstrate that no damage occurred or that it is significantly lower than the lump sum. The above provisions apply accordingly to payments of the purchase price for goods sold by third-party providers.</p>
            <p style="padding-left: 30px;">- Instant bank transfer</p>

            <p>(6) Certain payment methods may be excluded by the provider on a case-by-case basis.</p>
            <p>(7) The purchaser is not permitted to pay for the goods or services by sending cash or checks.</p>
            <p>(8) If the purchaser chooses an online payment method, they authorize the provider to collect the amounts due at the time of ordering.</p>
            <p>(9) If the provider offers payment in advance and the purchaser chooses this payment method, the purchaser must transfer the invoice amount to the provider's account within five calendar days after receipt of the order. The provider reserves the goods accordingly for five calendar days.</p>
            <p>(10) If the provider offers payment by credit card and the purchaser chooses this payment method, the purchaser expressly authorizes the provider to collect the amounts due.</p>
            <p>(11) If the provider offers payment by direct debit and the purchaser chooses this payment method, the purchaser grants the provider a SEPA basic mandate. If a payment transaction is reversed due to insufficient funds or incorrectly transmitted bank details, the purchaser is responsible for the costs.</p>
            <p>(12) If the provider offers payment in advance and the purchaser chooses this payment method, the purchaser undertakes to settle the invoice amount within 14 days after dispatch of the goods, without any deduction for discount.</p>
            <p>(13) If the purchaser is in default of payment, the provider reserves the right to claim damages for default.</p>
            <p style="text-align: left;"><strong><br>§ 8 </strong><strong>Registration and Termination</strong></p>
            <p style="text-align: left;">(1) Furthermore, the purchaser declares that they and, to their knowledge, no member of their household has been convicted of an intentional criminal offense endangering the safety of others, in particular, not for a criminal offense against sexual self-determination (Sections 174 et seq. of the German Criminal Code), a criminal offense against life (Sections 211 et seq. of the German Criminal Code), a criminal offense against physical integrity (Sections 223 et seq. of the German Criminal Code), a criminal offense against personal freedom (Sections 232 et seq. of the German Criminal Code), or for theft and embezzlement (Sections 242 et seq. of the German Criminal Code) or for robbery and extortion (Sections 249 et seq. of the German Criminal Code) or for drug abuse.</p>
            <p>(2) A user account is for their sole and personal use, and a user may not authorize third parties to use this account. A user may not transfer their account to third parties.</p>
            <p>(3) A user is, subject to reservation, entitled to deregister at any time without giving reasons in writing by post, email, or telephone. At the same time, there is the possibility to deactivate the user account completely and personally within the data and settings in the user account. The previously concluded contractual relationship is thereby terminated.</p>
            <p>(4) If a user has registered for a fee-based service, they can cancel it no later than <span id="span_id_kundigungsfrist_abo">90</span> days before the booking period. If this deadline is not met, the paid service will be extended by this period depending on the chosen booking period, and the cancellation will only become effective at the end of the subsequent booking period. Cancellation is possible by telephone, email, or letter and will be confirmed in writing by us. To allocate your cancellation, the full name, the registered email address, and the customer's address should be provided. In the case of cancellation by telephone, the individual telephone password is required.</p>
            <p>(5) <span id="span_id_name_online_shop">Everbuild</span> may terminate the contract at its discretion, with or without prior notice and without giving reasons, at any time. <span id="span_id_name_online_shop">Everbuild</span> also reserves the right to remove profiles and/or any content published on the website by or from the user. If <span id="span_id_name_online_shop">Everbuild</span> terminates the user's registration and/or removes profiles or published content of the user, <span id="span_id_name_online_shop">Everbuild</span> is not obliged to inform the user about the reason for the termination or removal.</p>
            <p>(6) Following the termination of any individual use of <span id="span_id_name_online_shop">Everbuild</span>'s services, <span id="span_id_name_online_shop">Everbuild</span> reserves the right to send information about this to other registered users with whom <span id="span_id_name_online_shop">Everbuild</span> assumes that they have been in contact with the user. <span id="span_id_name_online_shop">Everbuild</span>'s decision to terminate the user's registration and/or notify other users with whom <span id="span_id_name_online_shop">Everbuild</span> assumes the user has been in contact does not imply or in any way indicate that <span id="span_id_name_online_shop">Everbuild</span> makes statements about the individual character, general reputation, personal characteristics, or lifestyle of the user.</p>
            <p>(7) Users are obliged not to make intentional or fraudulent false statements in their profile and other areas of the portal. Such statements may result in civil legal action. Furthermore, the operator reserves the right to terminate the existing contractual relationship with immediate effect in such cases.</p>
            <p>(8) If a user's access is blocked due to a culpable breach of contract and/or the contractual relationship is terminated, the user must pay damages for the remaining term of the contract in the amount of the agreed remuneration minus the saved expenses. The amount of the saved expenses is fixed at a lump sum of 10% of the remuneration. It remains open to both parties to prove that the damage and/or saved expenses are actually higher or lower.</p>
            <p>(9) After termination of the contractual relationship, all user data will be deleted by <span id="span_id_name_online_shop">Everbuild</span>.</p>
            <p style="text-align: left;"><strong><br>§ 9 </strong><strong>Limitation of Liability (Services)</strong></p>
            <p style="text-align: left;">(1) <span id="span_id_name_online_shop">Everbuild</span> assumes no responsibility for the content and accuracy of the information in the registration and profile data of the purchasers as well as other content generated by the purchasers.</p>
            <p style="text-align: left;">(2) With regard to the sought or offered service, the contract is concluded exclusively between the respective participating purchasers. Therefore, <span id="span_id_name_online_shop">Everbuild</span> is not liable for services provided by participating purchasers. Accordingly, all matters concerning the relationship between the purchasers, including, without limitation, the services received by a seeker or payments due to purchasers, are to be directed directly to the respective party. <span id="span_id_name_online_shop">Everbuild</span> cannot be held responsible for this and expressly contradicts any liability claims of any kind, including claims, services, direct or indirect damages of any kind, whether known or unknown, disclosed or undisclosed, in any way related to the matters mentioned.</p>
            <p style="text-align: left;">(3) <span id="span_id_name_online_shop">Everbuild</span> is liable for damages resulting from injury to life, body, or health only if they are based on an intentional or negligent breach of duty by <span id="span_id_name_online_shop">Everbuild</span> or an intentional or negligent breach of duty by a legal representative or vicarious agent of <span id="span_id_name_online_shop">Everbuild</span>.</p>
            <p style="text-align: left;">(4) For other damages, insofar as they do not result from the violation of cardinal obligations (those obligations whose fulfillment enables the proper execution of the contract in the first place and on whose compliance the contractual partner may regularly rely), <span id="span_id_name_online_shop">Everbuild</span> Europe is only liable if they are based on an intentional or grossly negligent breach of duty by <span id="span_id_name_online_shop">Everbuild</span> or on an intentional or grossly negligent breach of duty by a legal representative or vicarious agent of <span id="span_id_name_online_shop">Everbuild</span>.</p>
            <p style="text-align: left;">(5) Compensation claims are limited to the foreseeable, typical damage. In the event of default, they amount to a maximum of 5% of the order value.</p>
            <p style="text-align: left;">(6) Compensation claims based on injury to life, body, or health or freedom shall become statute-barred after 30 years; otherwise, after 1 year, with the limitation period ending with the end of the year in which the claim arose and the creditor became aware of the circumstances giving rise to the claim and the person of the debtor, or would have had to become aware of them without gross negligence (§ 199 (1) of the German Civil Code).</p>
            <p style="text-align: left;">(7) The provider reserves the right to review the content of a text written by a user and uploaded files for compliance with law and order and, if necessary, to delete them in whole or in part.</p>
            <p style="text-align: left;"><strong><br>§ 10 </strong><strong>Setoff and Right of Retention</strong></p>
            <p>(1) The purchaser is only entitled to setoff if their counterclaim has been legally established or is undisputed by the provider.</p>
            <p>(2) The purchaser may only exercise a right of retention to the extent that their counterclaim is based on the same contractual relationship.</p>
            <p style="text-align: left;"><strong><br>§ 11 </strong><strong>Retention of Title</strong></p>
            <p style="text-align: left;"><span id="span_id_firma_mit_firmenzusatz">Everbuild</span> reserves the right of ownership of the goods until full payment has been made.</p>
            <p style="text-align: left;"><strong><br>§ 12 </strong><strong>Warranty Rights</strong></p>
            <p style="text-align: left;">(1) If the purchaser is a consumer, the warranty and liability for defects of the delivered item are governed by statutory provisions: Accordingly, purchasers in the European Union, in addition to their 30-day return guarantee, have warranty rights for a period of two years from delivery of the goods and can demand repair or replacement of products purchased on <span id="span_id_name_online_shop">Everbuild</span> if they prove to be defective or not as described. If the goods cannot be repaired or replaced within a reasonable time or without difficulty, you may request a refund or reduction of the purchase price.</p>
            <p style="text-align: left;">(2) In the case of used goods, the warranty period may be less than two years.</p>
            <p style="text-align: left;">(3) If the purchaser is not a consumer, defects are remedied by replacement or new performance.</p>
            <p style="text-align: left;">(4) If the purchaser is not a consumer, the limitation period is one year. This applies unless claims for damages and reimbursement of expenses are made for damage to body and health or for intent or gross negligence.</p>
            <p style="text-align: left;"><strong><br>§ 13 </strong><strong>Limitation of Liability (Products)</strong></p>
            <p style="text-align: left;">(1) The provider is liable for compensation claims of the purchaser arising from injury to life, body, health, or from the violation of essential contractual obligations, as well as for other damages based on their intentional or grossly negligent breach of duty or that of a legal representative or vicarious agent of the provider.</p>
            <p style="text-align: left;">(2) Essential contractual obligations are obligations whose fulfillment is necessary to achieve the objective of the contract.</p>
            <p style="text-align: left;">(3) The provider is liable for breaches of essential contractual obligations based on contract-typical, foreseeable damages, provided that the damage was caused simply negligently. This limitation does not apply to compensation claims of the purchaser based on injury to life, body, or health.</p>
            <p style="text-align: left;">(4) The provisions of the Product Liability Act remain unaffected.</p>
            <p style="text-align: left;">(5) To the extent that <span id="span_id_name_online_shop">Everbuild</span>'s liability is excluded or limited, this also applies to the personal liability of employees, representatives, and vicarious agents.</p>
            <p style="text-align: left;"><strong><br>§ 14 </strong><strong>Revocation Policy</strong></p>
            <p>(1) If the purchaser is a consumer, they have a right of revocation in accordance with the following provisions:</p>
            <p>(2) Right of Revocation</p>
            <p>You have the right to revoke this contract within fourteen days without giving any reason.</p>
            <p>The revocation period is fourteen days from the day on which you or a third party designated by you, who is not the carrier, took possession of the goods (or the last goods, partial shipment, or piece in the case of a contract for several goods in a single order or the delivery of goods in several partial shipments or pieces) or from the day of the conclusion of the contract, in the case of digital content not supplied on a physical medium (e.g., CDs or DVDs), without giving reasons for revocation.</p>
            <p>The revocation period for services is fourteen days from the date of conclusion of the contract.</p>
            <p>To exercise your right of revocation, you must inform us:</p>
            <p><span id="span_id_firma_mit_firmenzusatz">Everbuild</span></p>
            <p><span id="span_id_adresse_firma">Fallerweg 7<br>54516 Wittlich<br>Germany</span></p>
            <p>Email: <span id="span_id_e_mail_firma">nico.weber24@gmx.de</span></p>
            <p>by means of a clear statement (e.g., a letter sent by post, fax, or email) of your decision to revoke this contract. You can use the sample revocation form on our website or send us another clear statement. If you make use of this option, we will immediately (e.g., by email) send you confirmation of receipt of such revocation.</p>
            <p>To meet the revocation deadline, it is sufficient for you to send your communication concerning the exercise of the right of revocation before the revocation period expires and for you to return the goods to us within the period defined below via our online return center.</p>
            <p>For additional information on the scope, content, and explanations of the exercise, please contact our customer service.</p>
            <p>(3) Consequences of Revocation</p>
            <p>If you revoke this contract, we will refund you all payments we have received from you, including delivery costs (except for the additional costs arising from your choice of a different type of delivery than the cheapest standard delivery offered by us), without undue delay and no later than fourteen days from the date on which we receive notice of your revocation of this contract. For this refund, we will use the same means of payment that you used for the original transaction unless expressly agreed otherwise with you; in no case will you be charged for this refund.</p>
            <p>If you have requested that services begin during the revocation period, you shall pay us a reasonable amount corresponding to the proportion of services already provided by the time you inform us of the exercise of the right of revocation with regard to this contract compared to the total scope of the services provided for in the contract.</p>
            <p>We may refuse a refund until we have received the goods back or until you have provided evidence that you have returned the goods, whichever is earlier.</p>
            <p>You must return the goods to us immediately and in any event no later than fourteen days from the date on which you inform us of the revocation of this contract, to</p>
            <p><span id="span_id_firma_mit_firmenzusatz">Everbuild</span></p>
            <p><span id="span_id_adresse_firma">Fallerweg 7<br>54516 Wittlich<br>Germany</span> </p>
            <p>Email: <span id="span_id_e_mail_firma">nico.weber24@gmx.de</span></p>
            <p>To be returned or handed over. The deadline is met if you send the goods before the deadline of 14 days. You must bear the regular costs of returning the goods if the delivered goods correspond to the ordered ones and if the price of the goods to be returned does not exceed an amount of <span id="span_id_ab_welchem_betrag_ubernimmt_der_anbieter_lieferkosten">0</span> € (zero euros) or if, in the case of a higher price of the goods, you have not yet provided the consideration or a contractually agreed partial payment at the time of revocation. Otherwise, the return is free of charge for you. </p>
            <p>(4) Exceptions to the right of revocation</p>
            <p>You only have to pay for any loss in value of the goods if this loss in value is due to handling of the goods that is not necessary to examine their nature, properties, and functionality.</p>
            <p>The right of revocation does not exist or expires for the following contracts:</p>
            <ul>
                <li>for the delivery of goods which are not suitable for return due to reasons of health protection or hygiene and whose sealing has been removed after delivery or which have been inseparably mixed with other goods after delivery due to their nature;</li>
            </ul>
            <ul>
                <li>for the delivery of sound or video recordings or computer software in a sealed package, if the seal has been removed after delivery;</li>
            </ul>
            <ul>
                <li>for the delivery of goods made to customer specifications or clearly tailored to personal needs;</li>
            </ul>
            <ul>
                <li>for the delivery of goods which can spoil quickly or whose expiration date would quickly be exceeded;</li>
            </ul>
            <ul>
                <li>for services, if <span id="span_id_name_online_shop">Everbuild</span> has fully provided these and you have taken note of and expressly agreed to this before ordering, that we can begin with the provision of the service and you lose your right of revocation upon complete fulfillment of the contract;</li>
            </ul>
            <ul>
                <li>for the delivery of newspapers, periodicals or magazines, except for subscription contracts; and</li>
            </ul>
            <ul>
                <li>for the delivery of alcoholic beverages, the price of which was agreed upon conclusion of the purchase contract, but whose delivery can only take place after 30 days and whose current value depends on fluctuations in the market over which the entrepreneur has no influence.</li>
            </ul>

            <p style="text-align: left;"><strong><br>§ 15 </strong><strong>Exclusion of the right of withdrawal</strong></p>
            <p style="text-align: left;">(1) The right of withdrawal does not exist for contracts</p>
            <ul>
                <li>for the delivery of goods that are not prefabricated and for the production of which an individual selection or determination by the consumer is decisive or which are clearly tailored to the personal needs of the consumer;</li>
            </ul>
            <ul>
                <li>for the delivery of goods which can spoil quickly or whose expiration date would quickly be exceeded;</li>
            </ul>
            <p style="text-align: left;">(2) The right of withdrawal expires prematurely for contracts</p>
            <ul>
                <li>for the delivery of sealed goods which are not suitable for return for reasons of health protection or hygiene if their sealing has been removed after delivery;</li>
            </ul>
            <ul>
                <li>for the delivery of goods if, after delivery, they have been inseparably mixed with other goods due to their nature;</li>
            </ul>
            <ul>
                <li>for the delivery of sound or video recordings or computer software in a sealed package if the seal has been removed after delivery.</li>
            </ul>
            <p style="text-align: left;"><br><strong>§ 16 </strong><strong>Data Protection</strong></p>
            <p>(1) Should personal data (e.g., name, address, email address) be collected, we undertake to obtain your prior consent. We undertake not to disclose data to third parties unless you have previously consented.</p>
            <p>(2) We would like to point out that the transmission of data over the Internet (e.g., by email) may have security vulnerabilities. Therefore, flawless and trouble-free protection of third-party data cannot be completely guaranteed. In this regard, our liability is excluded.</p>
            <p>(3) Third parties are not authorized to use contact data for commercial activities unless the provider has previously obtained written consent from the persons concerned.</p>
            <p>(4) You have the right at any time to obtain complete and free information from <span id="span_id_name_online_shop">Everbuild</span> about the data concerning you.</p>
            <p>(5) Furthermore, there is a right to correction/deletion of data/restriction of processing for the user.</p>
            <p>(6) Further information on data protection can be found in the separate privacy policy.</p>
            <p style="text-align: left;"><br><strong>§ 17 </strong><strong>Cookies</strong></p>
            <p>(1) Cookies may be used to display the product range. Cookies are small text files that are stored locally in the cache of the visitor's Internet browser.</p>
            <p>(2) Numerous websites and servers use cookies. Many cookies contain a so-called cookie ID. A cookie ID is a unique identifier of the cookie. It consists of a character string through which Internet pages and servers can be assigned to the specific Internet browser in which the cookie was stored. This allows the visited Internet pages and servers to distinguish the individual browser of the data subject from other Internet browsers that contain other cookies. A specific Internet browser can be recognized and identified via the unique cookie ID.</p>
            <p>(3) The use of cookies enables us to provide users of this website with more user-friendly services that would not be possible without setting the cookies.</p>
            <p>(4) We would like to point out that some of these cookies are transmitted from our server to your computer system, usually so-called session-related cookies. Session-related cookies are characterized by the fact that they are automatically deleted from your hard drive at the end of the browser session. Other cookies remain on your computer system and enable us to recognize your computer system during your next visit (so-called persistent cookies).</p>
            <p>(5) You can object to the storage of cookies; for this purpose, there is a banner available to you which you can object to/accept.</p>
            <p>(6) Of course, you can set your browser so that no cookies are stored on the hard drive or already stored cookies are deleted. Instructions on how to prevent and delete cookies can be found in the help function of your browser or software manufacturer.</p>
            <p style="text-align: left;"><strong><br>§ 18 </strong><strong>Final Provisions</strong></p>
            <p style="text-align: left;">(1) The contract language is German and English.</p>
            <p>(2) We do not offer products or services for purchase by minors. Our products for children can only be purchased by adults. If you are under 18, you may only use <span id="span_id_name_online_shop">Everbuild</span> with the involvement of a parent or guardian.</p>
            <p>(3) If you violate these terms and we do not take action against it, we will still be entitled to exercise our rights in any other situation where you violate these sales conditions.</p>
            <p style="text-align: left;">(4) We reserve the right to make changes to our website, regulations, terms and conditions, including these terms and conditions, at any time. For your order, the sales conditions, contractual conditions, and terms and conditions that are in effect at the time of your order apply, unless a change to these conditions is required by law or by regulatory order (in which case they also apply to orders you have previously placed). If a provision in these sales conditions is ineffective, void, or for any reason unenforceable, that provision shall be deemed severable and shall not affect the validity and enforceability of the remaining provisions.</p>
            <p style="text-align: left;">(5) The invalidity of one provision does not affect the validity of the other provisions of the contract. Should this occur, the provision shall be replaced by another legally permissible provision which corresponds to the purpose and intent of the invalid provision.</p>
            <p> Date: 07.04.2024</p>
        {/if}
    </div>
</div>